# Generated by Django 3.1 on 2020-08-17 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0006_auto_20200817_1742'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseslist',
            old_name='lenght',
            new_name='items_count',
        ),
    ]
