# Generated by Django 3.1 on 2020-10-13 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0007_auto_20200817_1811'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ('ind', 'creation_time')},
        ),
        migrations.AlterModelOptions(
            name='purchaseslist',
            options={'ordering': ('ind', 'creation_time')},
        ),
        migrations.RemoveField(
            model_name='purchaseslist',
            name='items_count',
        ),
    ]
