# Generated by Django 3.1 on 2020-10-13 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0008_auto_20201013_0512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creation time'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='ind',
            field=models.IntegerField(verbose_name='Purchase index'),
        ),
        migrations.AlterField(
            model_name='purchaseslist',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creation time'),
        ),
        migrations.AlterField(
            model_name='purchaseslist',
            name='ind',
            field=models.IntegerField(verbose_name='List index'),
        ),
        migrations.AlterField(
            model_name='purchaseslist',
            name='last_change',
            field=models.DateTimeField(auto_now=True, verbose_name='Last change'),
        ),
    ]
