# Generated by Django 3.1 on 2020-10-13 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0009_auto_20201013_0613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='ind',
            field=models.IntegerField(blank=True, verbose_name='Purchase index'),
        ),
        migrations.AlterField(
            model_name='purchaseslist',
            name='ind',
            field=models.IntegerField(blank=True, verbose_name='List index'),
        ),
    ]
