# Generated by Django 3.1 on 2020-10-14 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0010_auto_20201013_0614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='title',
            field=models.CharField(max_length=256, verbose_name='Purchase title'),
        ),
        migrations.AlterField(
            model_name='purchaseslist',
            name='title',
            field=models.CharField(max_length=256, verbose_name='List title'),
        ),
    ]
