# Generated by Django 3.1 on 2020-08-17 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_customuser_condition'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='lists_count',
            new_name='items_count',
        ),
    ]
