# Generated by Django 3.1 on 2020-08-17 11:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200817_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_change',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last action'),
        ),
    ]
