# Generated by Django 3.1 on 2020-10-13 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_last_change'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='items_count',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_joining',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date of joining'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=55, null=True, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_change',
            field=models.DateTimeField(auto_now=True, verbose_name='Last action'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=55, null=True, verbose_name='Second name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='nickname',
            field=models.CharField(blank=True, max_length=55, null=True, verbose_name='Nickname'),
        ),
    ]
