# Generated by Django 3.1 on 2020-10-14 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20201013_0512'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_bot',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='telegram_id',
            field=models.IntegerField(unique=True, verbose_name='Telegram id'),
        ),
    ]
